kind: Deployment
apiVersion: apps/v1
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  # how many pods and indicate which strategy we want for rolling update
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      # secrets and config
      volumes:
        - name: sftp-client-public-keys
          secret:
            secretName: sftp-client-public-keys
        - name: sftp-host-keys
          secret:
            secretName: sftp-host-keys
            defaultMode: 0600
      containers:
        # the sftp server itself
        - name: sftp
          # use kalioz/sftp:latest instead of atmoz/sftp:latest if you need arm compatibility
          image: atmoz/sftp:latest
          imagePullPolicy: IfNotPresent
          # create users and dirs
          # user:password:uid:gid:directories
          args: ["myUser::::incoming,outgoing"]
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /home/myUser/.ssh/keys
              name: sftp-client-public-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key
              name: sftp-host-keys
              subPath: ssh_host_rsa_key
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key.pub
              name: sftp-host-keys
              subPath: ssh_host_rsa_key.pub
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key
              name: sftp-host-keys
              subPath: ssh_host_ed25519_key
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              name: sftp-host-keys
              subPath: ssh_host_ed25519_key.pub
              readOnly: true
          resources: {}
