apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-nginx-cm
  labels:
    app: webserver
data:
  default.conf: |-
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        location /site1 {
          return 200 "This is WebServer for site1 Listening on 80";
        }
        location /site2 {
          return 200 "This is WebServer for site2 Listening on 80";
        }
        location /healtz {
          return 200;
        }
    }


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          imagePullPolicy: IfNotPresent
          image: nginx:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healtz
              port: 80
            periodSeconds: 10
            timeoutSeconds: 1  
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: configmap-volume
      volumes:
      - name: configmap-volume
        configMap:
          name: webserver-nginx-cm

---

apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: sebserver
spec:
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webserver
  labels:
     app: webserver
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /site1
        backend:
          serviceName: webserver
          servicePort: 80
      - path: /site2
        backend:
          serviceName: webserver
          servicePort: 80

