apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - secretName: nginx-tls
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80