apiVersion: v1
kind: Pod
metadata:
  name: webserver1
spec:
  nodeName: aks-cpu120-72510697-vmss0001ie
  containers:
  - name: webserver
    image: sesantia2020/webserver:3.2
    env:
    - name: LISTEN_PORT
      value: "8080"
    - name: SERVER_NAME
      value: "webserver1.internal.com"
    ports:
    - containerPort: 8080
      protocol: TCP