apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver1-deployment
spec:
  selector:
    matchLabels:
      app: webserver-1
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver-1
    spec:
      containers:
        - name: webserver-1
          imagePullPolicy: Always
          image: nginx:latest
          ports:
            - containerPort: 8083
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: configmap-volume
      volumes:
      - name: configmap-volume
        configMap:
          name: webserver1-nginx-cm
      livenessProbe:
        httpGet:
          path: /
          port: 8083
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver1-nginx-cm
data:
  default.conf: |-
    server {
        listen 8083 default_server;
        server_name  webserver-1.internal.com;
        root /usr/share/nginx/html;
        index index.html;
        location / {
          return 200 "This is WebServer-1 Listening on 8083";
        }
    }