apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver1
  template:
    metadata:
      labels:
        app: webserver1
    spec:
      containers:
      - name: webserver1
        image: sesantia2020/webserver:3.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LISTEN_PORT
          value: "8080"
        - name: SERVER_NAME
          value: "webserver1.internal.com"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
            - name: Host
              value: webserver1.internal.com
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: webserver1
spec:
  selector:
    app: webserver1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080